### ISSUE TITLE
Problem converting pose_landmark (full)

### ISSUE THREAD

**Issue by grpinto** [PINTO0309/tflite2tensorflow#40]
### Issue Type

Performance

### OS

Mac OS

### OS architecture

Other

### Programming Language

Python

### Framework

TensorFlowLite

### Download URL for tflite file

https://developers.google.com/mediapipe/solutions/vision/pose_landmarker

### Convert Script

user@docker-desktop:~/workdir$ tflite2tensorflow --model_path /Users/kingsize/Documents/binedgeml/pose_detector.tflite --flatc_path ../flatc --schema_path ../schema.fbs --output_pb

### Description

I am trying to install a mediapipe file that you can download from the mediapipe website https://developers.google.com/mediapipe/solutions/vision/pose_landmarker , I downloaded the full file, unzip it, and now I have two models, I am trying to converto to tflite but it doesn't seem to be working for some reason an dI am getting this error, can somebody help me to do this operation ?

### Relevant Log Output

```shell
Traceback (most recent call last):   File "/usr/local/bin/tflite2tensorflow", line 6614, in <module>     main()   File "/usr/local/bin/tflite2tensorflow", line 5861, in main     ops, json_tensor_details, op_types, full_json = parse_json(jsonfile_path)   File "/usr/local/bin/tflite2tensorflow", line 247, in parse_json     j = json.load(open(jsonfile_path)) FileNotFoundError: [Errno 2] No such file or directory: './/Users/kingsize/Documents/binedgeml/pose_detector.json'
```

**Comment by PINTO0309** [comment]
https://github.com/PINTO0309/PINTO_model_zoo#6-2d3d-humananimal-pose-estimation
